name: Publish Marketplace Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate TypeScript types
      run: npm run types:generate
      
    - name: Verify types generation
      run: |
        echo "Checking if types were generated..."
        ls -la types/
        ls -la types/integrations/ || echo "No integrations directory found"
        ls -la types/adapters/ || echo "No adapters directory found"
        
    - name: Build package
      run: npm run build
      
    - name: Publish to NPM
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Automated release with generated types for:
          - Adapters: $(find types/adapters -name "*.d.ts" | wc -l) files
          - Integrations: $(find types/integrations -name "*.d.ts" | wc -l) files
        draft: false
        prerelease: false