name: Marketplace Validation

on:
  pull_request:
    paths:
      - 'features/**'
      - 'adapters/**'
      - 'connectors/**'
      - 'scripts/**'
      - 'package.json'
  push:
    branches: [main, develop]
    paths:
      - 'features/**'
      - 'adapters/**'
      - 'connectors/**'
      - 'scripts/**'
      - 'package.json'

jobs:
  validate-marketplace:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for comparison
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate schemas from contracts
        run: |
          echo "🔧 Generating schemas from TypeScript contracts..."
          npm run generate:schemas
      
      - name: Generate marketplace manifest
        run: |
          echo "📋 Generating marketplace manifest..."
          npm run generate:manifest
      
      - name: Run contract correctness validation
        run: |
          echo "🔍 Running contract correctness validation..."
          npm run validate:correctness
      
      - name: Check contract compliance changes
        id: compliance-check
        run: |
          echo "📊 Analyzing contract compliance changes..."
          
          # Check if the validation passed
          if [ $? -eq 0 ]; then
            echo "✅ Contract validation passed"
            echo "compliance_status=passed" >> $GITHUB_OUTPUT
          else
            echo "❌ Contract validation failed"
            echo "compliance_status=failed" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment PR with validation results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            // Generate simple validation report
            let report = '## 🔍 Marketplace Validation Report\n\n';
            
            // Check if validation passed
            const validationPassed = '${{ steps.compliance-check.outputs.compliance_status }}' === 'passed';
            
            if (validationPassed) {
              report += `### ✅ **Validation Status: PASSED**\n\n`;
              report += `All contract validations completed successfully!\n\n`;
            } else {
              report += `### ❌ **Validation Status: FAILED**\n\n`;
              report += `Contract validation failed. Please check the logs for details.\n\n`;
            }
            
            // Add recommendations
            report += `### 💡 Next Steps\n\n`;
            if (validationPassed) {
              report += `- ✅ All contracts are properly implemented\n`;
              report += `- ✅ Schema generation completed successfully\n`;
              report += `- ✅ Contract correctness validation passed\n`;
            } else {
              report += `- ❌ Review contract implementation errors\n`;
              report += `- ❌ Check template file existence and syntax\n`;
              report += `- ❌ Verify contract hook signatures match implementations\n`;
            }
            
            report += `\n---\n`;
            report += `*This report was generated by the Marketplace Validation System*`;
            
            // Post the comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
      
      - name: Fail on critical compliance issues
        if: steps.compliance-check.outputs.compliance_status == 'failed'
        run: |
          echo "❌ Critical compliance issues detected!"
          echo "Please review the validation report and fix compliance issues before merging."
          exit 1
